version: "3"
services:
  dakl-fe:
    build: .
    ports:
      - "4590:80"
    container_name: DAKLFE
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
