version: "3.8"
services:
  dakl-fe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4590:80"
    container_name: DAKLFE
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          memory: 256M
