name: Loan management Frontend CI/CD Pipeline

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy source code to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.FRONTEND_SERVER_HOST }}
          username: ${{ secrets.FRONTEND_SERVER_USER }}
          password: ${{ secrets.FRONTEND_SERVER_PASSWORD }}
          source: "./*"
          target : "/root/DAKL/FE"
          timeout: 600 # Tăng thời gian chờ lên 10 phút
          debug: true # Bật thông tin gỡ lỗi

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.FRONTEND_SERVER_HOST }}
          username: ${{ secrets.FRONTEND_SERVER_USER }}
          password: ${{ secrets.FRONTEND_SERVER_PASSWORD }}
          port: 22
          script: |
            cd /root/DAKL/FE
            sudo docker compose down       
            docker compose up --build -d
