name: Loan management Frontend CI/CD Pipeline

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create target directory
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.FRONTEND_SERVER_HOST }}
          username: ${{ secrets.FRONTEND_SERVER_USER }}
          password: ${{ secrets.FRONTEND_SERVER_PASSWORD }}
          port: 22
          script: mkdir -p /root/DAKL/FE

      - name: Copy source code to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.FRONTEND_SERVER_HOST }}
          username: ${{ secrets.FRONTEND_SERVER_USER }}
          password: ${{ secrets.FRONTEND_SERVER_PASSWORD }}
          source: "./dist/*" # Adjust this based on your build output directory
          target: "/root/DAKL/FE"
          port: 22
          debug: true

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.FRONTEND_SERVER_HOST }}
          username: ${{ secrets.FRONTEND_SERVER_USER }}
          password: ${{ secrets.FRONTEND_SERVER_PASSWORD }}
          port: 22
          script: |
            cd /root/DAKL/FE
            sudo docker compose down       
            docker compose up --build -d
